[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[template.environment]
  ELEVENTY_ENV = "production"
