backend:
  name: git-gateway
  branch: main

# Media and asset configuration
media_folder: "assets/images"
public_folder: "/assets/images"

# Editorial workflow (optional) - enables drafts
publish_mode: editorial_workflow

# Content collections
collections:
  # News Articles Collection
  - name: "news"
    label: "News Articles"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "news"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publication Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Summary", name: "summary", widget: "text", required: false, hint: "Short summary for homepage display"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", default: ["news"], allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}

  # Council Members Collection
  - name: "council-members"
    label: "Council Members"
    folder: "src/council"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Photo", name: "photo", widget: "image", required: false}
      - {label: "Category", name: "category", widget: "select", options: ["Executive", "Appointed", "Elected", "Ex-Officio", "Committee", "Judicial Board"]}
      - {label: "Order", name: "order", widget: "number", default: 100, hint: "Lower numbers appear first in the list"}
      - {label: "Bio", name: "body", widget: "markdown", required: false}

  # Pages Collection (for editable content on static pages)
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/about.njk"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown"}
      
      - file: "src/contact.njk"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Office Location", name: "office", widget: "string", required: false}
          - {label: "Office Hours", name: "hours", widget: "string", required: false}
          - {label: "Content", name: "body", widget: "markdown"}